### ISSUE TITLE
Database: table prefix support ?

### ISSUE THREAD

**Issue by Gounlaf** [Wolnosciowiec/file-repository#10]
I need table prefix support; I found this library `val/doctrine-table-prefix-service-provider`, but I had to fork it fo Pimple 3.x support.

It's not a "common" requirement, so IMHO it should not be embed; but if you need a PR, modifications are done here: https://github.com/Gounlaf/file-repository/tree/enhancement/database-table-prefix

**Comment by blackandred** [comment]
Thanks, I will take a look at it tommorow. We could together join the changes into mainline code.

**Comment by blackandred** [comment]
I think this actually could be very helpful feature on shared hosting - this project aim to be accessible on shared hostings, it has to provide a cheap alternative.
So maybe we could integrate this feature by putting it directly into the repository?
Instead of forking that 2 tiny classes that are required just copy them, attach information about author, add unit tests?

**Comment by Gounlaf** [comment]
> So maybe we could integrate this feature by putting it directly into the repository?
> Instead of forking that 2 tiny classes that are required just copy them, attach information about author, add unit tests?

I can do a PR, instead for unit tests =/ (I'm not friend with them :( )

**Comment by Gounlaf** [comment]
PR #11

**Comment by blackandred** [comment]
> I'm not friend with them :(

It's ok, I can help you wit them :wink:

**Comment by blackandred** [comment]
Implemented in https://github.com/Wolnosciowiec/file-repository/pull/14

**Comment by blackandred** [comment]
Merged.
